### ISSUE TITLE
Update django-classy-tags requirement

### ISSUE THREAD

**Issue by mikemcgowan** [coagulant/django-twitter-tag#43]
Hi there,

[django-cms](https://github.com/divio/django-cms) requires `django-classy-tags>=0.5` but this requires `django-classy-tags==0.4` which is obviously impossible to satisfy both.

Our production system is running `django-classy-tags==0.6.2` so this would appear to work fine with `>=0.4`. Would it be possible to get this updated?

Because at present, [pip-tools](https://github.com/nvie/pip-tools) is complaining:

```
Could not find a version that matches django-classy-tags==0.4,>=0.5
```

**Comment by coagulant** [comment]
Will fix it, for sure.

I'm not using django-twiiter-tag anymore, care to take over maintaining this package?

**Comment by coagulant** [comment]
Please feel free to reopen if this does not solve your problem )

**Comment by mikemcgowan** [comment]
Thank you!

I'll ask my colleague who added it to our `requirements.txt` whether he's able to take over maintaining it.
